### ISSUE TITLE
Move this repo under the "github" organization

### ISSUE THREAD

**Issue by JamesMGreene** [github/review-pull-requests-at-github-template#1]
For security, it is now a requirement for template repos to be in the same org as their corresponding course definition repo.

As such, this template repo must be moved under the `github` organization.

After the move, we also need to verify that the Learning Lab integrations are still active on it.

cc: @github/learning-engineering

**Comment by beardofedu** [comment]
Added this to my calendar the week after Universe to get this done @JamesMGreene

**Comment by beardofedu** [comment]
@JamesMGreene we sync up to walk through this process, don't want to cause any problems since the course is currently live. ❤️

**Comment by JamesMGreene** [comment]
@beardofedu It would basically be like when we moved the corresponding course definition repo into the `github` org. I think you may be more in-the-know on how that transition went that I am.

Basic steps:
 1. Get this repo (`githubtraining/review-pull-requests-at-github-template`) moved into the `github` org (`github/review-pull-requests-at-github-template`) by an org admin
 2. Merge this PR in the corresponding course repo: https://github.com/github/review-pull-request/pull/1
 3. Allow a little time for the new course version/release to be created
 4. Register for the course and ensure a learner's repo is successfully created from the template

**Comment by JamesMGreene** [comment]
A quick note regarding the last step outlined:
 > [x] Register for the course and ensure a learner's repo is successfully created from the template repo

Not too surprisingly, I did end up issuing a manual sync of this course in order to get the template repo clones on each Heroku dyno all synced up.

**Comment by JamesMGreene** [comment]
Verified that the app is indeed already installed for `githubschool`:

https://github.com/organizations/githubschool/settings/installations/344649

![image](https://user-images.githubusercontent.com/417751/50113890-d222ca00-0208-11e9-8f56-c7ae00949afe.png)

.
.
.

![image](https://user-images.githubusercontent.com/417751/50113911-e070e600-0208-11e9-8380-961dda9df50e.png)

**Comment by JamesMGreene** [comment]
I'm thinking this is a discrepancy between the registration and the installation from the following code:

https://github.com/github/learning-lab/blob/9875d778c992843fc1c0ff621297e24bf4f2e26b/lib/server/routes/install.js#L11-L19

![image](https://user-images.githubusercontent.com/417751/50114631-9db00d80-020a-11e9-82cb-57b960c2c88e.png)

When grabbing the `installation`, we assume it is associated with the `req.user` rather than the `course.Organization.LearningOrg`.

Sound about right, @JasonEtco?
